const sprintf = require('sprintf');
const util = require('util');
const logger = require('../util/logger');
const headers = 'Previews Code,Quantity,Title,Price,Publisher,Comment\n';
const row = '%s,%d,%s,%s,%s,%s\n';

module.exports = (req, res, next) => {
  const order = undefined;

  console.log("Foo: " + util.inspect(req.body));
  if (!req.body.encodeddata) {
    console.log("A");
    console.log("Foo: " + req.body);
    return next({ status: 400, message: "Invalid request"});
  }

  try {
    order = JSON.parse(req.body.encodeddata);
  } catch (err) {
    console.log("B");
    console.log("Foo: " + req.body);
    return next({ status: 400, message: "Invalid request"});
  }

  if (!order.line_items || !order.line_items.length) {
    console.log("C");
    return next({
      status: 422,
      message: "No order details found in request"
    });
  }

  let csv = headers;

  for (let i = 0; i < order.line_items.length; i++) {
    const lineItem = order.line_items[i];
    csv += sprintf(row, lineItem.previews,
                          lineItem.quantity,
                          lineItem.title,
                          lineItem.price,
                          lineItem.publisher,
                          lineItem.comment);
  }

  csv += ",,Total," + (order.order_total / 100) + ",\n";
  csv += "\nGenerated by Ace My Order";

  res.setHeader("Content-type", "text/csv");
  res.setHeader("Content-Disposition", "filename=order" + order.issue + ".csv");
  res.setHeader("Pragma", "no-cache");
  res.setHeader("Expires", "0");
  res.send(csv);
}
