const sprintf = require('sprintf');
const headers = 'Previews Code,Quantity,Title,Price,Publisher,Comment\n';
const row = '%s,%d,%s,%s,%s,%s\n';
const logger = require('../util/logger');

module.exports = (req, res, next) => {
  let order = undefined;

  if (!req.body.order) {
    var err = new Error('No form data found');
    err.status = 400;

    return next(err);
  }

  order = req.body.order;

  let csv = headers;
  let orderTotal = 0;
  order.forEach((lineItem) => {
    csv += sprintf(row, lineItem.previews,
                          lineItem.quantity,
                          lineItem.title,
                          lineItem.price,
                          lineItem.publisher,
                          lineItem.comment);

    orderTotal += (lineItem.quantity * +lineItem.price);
  });

  csv += ",,Total," + orderTotal.toFixed(2) + ",\n";
  csv += "\nGenerated by Ace My Order";

  res.setHeader("Content-type", "text/csv");
  res.setHeader("Content-Disposition", "filename=order" + order.issue + ".csv");
  res.setHeader("Pragma", "no-cache");
  res.setHeader("Expires", "0");
  res.send(csv);
}
